# syntax = edrevo/dockerfile-plus

FROM osrf/ros:humble-desktop-full AS amd64_build_state

INCLUDE+ docker/Dockerfile.root.common

# vscode server
RUN  curl -fOL https://github.com/coder/code-server/releases/download/v4.104.2/code-server_4.104.2_amd64.deb && \
    dpkg -i code-server_4.104.2_amd64.deb && \
    rm code-server_4.104.2_amd64.deb

INCLUDE+ docker/Dockerfile.user.common
INCLUDE+ docker/Dockerfile.entrypoint.common